name: Auto update data

on: 
  schedule:
    - cron: '0 7-10 * * *'

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Fetch data version
        run: |
          curl -sL https://api.github.com/repos/Kengxxiao/ArknightsGameData/commits | grep -m1 "CN UPDATE" > version/data
          if [ -n "$(git status --porcelain)" ]; then
            echo "::set-env name=UPDATE::1"
          fi
      - uses: actions/setup-python@v1
        if: env.UPDATE==1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Update data and prepare push
        if: env.UPDATE==1
        run: |
          pip install requests
          python ./tools/extractMaterials.py
          python ./tools/extractStages.py
          git config --global user.name "Neko Bot"
          git config --global user.email "graueneko@gmail.com"
          git checkout "${GITHUB_REF:11}"
          git commit -am "数据更新"
      - name: Setup Github
        if: env.UPDATE==1
        run: git remote set-url origin https://x-access-token:$TOKEN@$REPO
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: github.com/graueneko/aktools.git
      - name: Setup Coding
        if: env.UPDATE==1
        run: git remote set-url --add origin https://$TOKEN@$REPO
        env:
          TOKEN: ${{ secrets.CODING_TOKEN }}
          REPO: e.coding.net/graueneko/aktools.git
      - name: Do push
        if: env.UPDATE==1
        run: git push
    env:
      CI: true
      UPDATE: 0
